module.exports = {
  "PAIRS": {
    "USDT": {
      "value": "USDT",
      "label": "USDT",
      "assets": ["BTC", "ETH", "BNB", "BCC", "NEO", "LTC", "QTUM", "ADA", "XRP", "EOS", "TUSD", "IOTA", "XLM", "ONT", "TRX", "ETC", "ICX", "VEN", "NULS", "VET", "PAX", "BCHABC", "BCHSV", "USDC", "LINK", "WAVES", "BTT", "USDS", "ONG", "HOT", "ZIL", "ZRX", "FET", "BAT", "XMR", "ZEC", "IOST", "CELR", "DASH", "NANO", "OMG", "THETA", "ENJ", "MITH", "MATIC", "ATOM", "TFUEL", "ONE", "FTM", "ALGO", "USDSB", "GTO", "ERD", "DOGE", "DUSK", "ANKR", "WIN", "COS", "NPXS", "COCOS", "MTL", "TOMO", "PERL", "DENT", "MFT", "KEY", "STORM", "DOCK", "WAN", "FUN", "CVC", "CHZ", "BAND", "BUSD", "BEAM", "XTZ", "REN", "RVN", "HC", "HBAR", "NKN", "STX", "KAVA", "ARPA", "IOTX", "RLC", "MCO", "CTXC", "BCH", "TROY", "VITE", "FTT", "EUR", "OGN", "DREP", "BULL", "BEAR", "ETHBULL", "ETHBEAR", "TCT", "WRX", "BTS", "LSK", "BNT", "LTO", "EOSBULL", "EOSBEAR", "XRPBULL", "XRPBEAR", "STRAT", "AION", "MBL", "COTI", "BNBBULL", "BNBBEAR", "STPT", "WTC", "DATA", "XZC", "SOL", "CTSI", "HIVE", "CHR", "BTCUP", "BTCDOWN", "GXS", "ARDR", "LEND", "MDT", "STMX", "KNC", "REP", "LRC", "PNT", "COMP", "BKRW", "SC", "ZEN", "SNX", "ETHUP", "ETHDOWN", "ADAUP", "ADADOWN", "LINKUP", "LINKDOWN", "VTHO", "DGB", "GBP", "SXP", "MKR", "DAI", "DCR", "STORJ", "BNBUP", "BNBDOWN", "XTZUP", "XTZDOWN", "MANA", "AUD", "YFI", "BAL", "BLZ", "IRIS", "KMD", "JST", "SRM", "ANT", "CRV", "SAND", "OCEAN", "NMR", "DOT", "LUNA", "RSR", "PAXG", "WNXM", "TRB", "BZRX", "SUSHI", "YFII", "KSM", "EGLD", "DIA", "RUNE", "FIO", "UMA", "EOSUP", "EOSDOWN", "TRXUP", "TRXDOWN", "XRPUP", "XRPDOWN", "DOTUP", "DOTDOWN", "BEL", "WING", "LTCUP", "LTCDOWN", "UNI", "NBS", "OXT", "SUN", "AVAX", "HNT", "FLM", "UNIUP", "UNIDOWN", "ORN", "UTK", "XVS", "ALPHA", "AAVE", "NEAR", "SXPUP", "SXPDOWN", "FIL", "FILUP", "FILDOWN", "YFIUP", "YFIDOWN", "INJ", "AUDIO", "CTK", "BCHUP", "BCHDOWN", "AKRO", "AXS", "HARD", "DNT", "STRAX", "UNFI", "ROSE", "AVA", "XEM", "AAVEUP", "AAVEDOWN", "SKL", "SUSD", "SUSHIUP", "SUSHIDOWN", "XLMUP", "XLMDOWN", "GRT", "JUV", "PSG", "1INCH", "REEF", "OG", "ATM", "ASR", "CELO", "RIF", "BTCST", "TRU", "CKB", "TWT", "FIRO"]
    },
    "ETH": {
      "value": "ETH",
      "label": "ETH",
      "assets": ["QTUM", "EOS", "SNT", "BNT", "BNB", "OAX", "DNT", "MCO", "ICN", "WTC", "LRC", "OMG", "ZRX", "STRAT", "SNGLS", "BQX", "KNC", "FUN", "SNM", "NEO", "IOTA", "LINK", "XVG", "SALT", "MDA", "MTL", "SUB", "ETC", "MTH", "ENG", "ZEC", "AST", "DASH", "BTG", "EVX", "REQ", "VIB", "HSR", "TRX", "POWR", "ARK", "YOYO", "XRP", "MOD", "ENJ", "STORJ", "VEN", "KMD", "RCN", "NULS", "RDN", "XMR", "DLT", "AMB", "BCC", "BAT", "BCPT", "ARN", "GVT", "CDT", "GXS", "POE", "QSP", "BTS", "XZC", "LSK", "TNT", "FUEL", "MANA", "BCD", "DGD", "ADX", "ADA", "PPT", "CMT", "XLM", "CND", "LEND", "WABI", "LTC", "TNB", "WAVES", "GTO", "ICX", "OST", "ELF", "AION", "NEBL", "BRD", "EDO", "WINGS", "NAV", "LUN", "TRIG", "APPC", "VIBE", "RLC", "INS", "PIVX", "IOST", "CHAT", "STEEM", "NANO", "VIA", "BLZ", "AE", "RPX", "NCASH", "POA", "ZIL", "ONT", "STORM", "XEM", "WAN", "WPR", "QLC", "SYS", "GRS", "CLOAK", "GNT", "LOOM", "BCN", "REP", "TUSD", "ZEN", "SKY", "CVC", "THETA", "IOTX", "QKC", "AGI", "NXS", "DATA", "SC", "NPXS", "KEY", "NAS", "MFT", "DENT", "ARDR", "HOT", "VET", "DOCK", "PHX", "HC", "PAX", "STMX", "WBTC", "SCRT", "AAVE", "EASY", "RENBTC", "SLP", "CVP", "STRAX", "FRONT", "HEGIC", "SUSD", "COVER", "GLM", "GHST", "DF", "GRT", "DEXE", "FIRO", "BETH"]
    },
    "BNB": {
      "value": "BNB",
      "label": "BNB",
      "assets": ["VEN", "YOYO", "POWR", "NULS", "RCN", "RDN", "DLT", "WTC", "AMB", "BCC", "BAT", "BCPT", "NEO", "QSP", "BTS", "XZC", "LSK", "IOTA", "ADX", "CMT", "XLM", "CND", "WABI", "LTC", "WAVES", "GTO", "ICX", "OST", "AION", "NEBL", "BRD", "MCO", "NAV", "TRIG", "APPC", "RLC", "PIVX", "STEEM", "NANO", "VIA", "BLZ", "AE", "RPX", "NCASH", "POA", "ZIL", "ONT", "STORM", "QTUM", "XEM", "WAN", "SYS", "QLC", "ADA", "GNT", "LOOM", "BCN", "REP", "TUSD", "ZEN", "SKY", "EOS", "CVC", "THETA", "XRP", "AGI", "NXS", "ENJ", "TRX", "ETC", "SC", "NAS", "MFT", "ARDR", "VET", "POLY", "PHX", "GO", "PAX", "RVN", "DCR", "USDC", "MITH", "REN", "BTT", "ONG", "HOT", "ZRX", "FET", "XMR", "ZEC", "IOST", "CELR", "DASH", "OMG", "MATIC", "ATOM", "PHB", "TFUEL", "ONE", "FTM", "ALGO", "ERD", "DOGE", "DUSK", "ANKR", "WIN", "COS", "COCOS", "TOMO", "PERL", "CHZ", "BAND", "BEAM", "XTZ", "HBAR", "NKN", "STX", "KAVA", "ARPA", "CTXC", "BCH", "TROY", "VITE", "FTT", "OGN", "DREP", "TCT", "WRX", "LTO", "STRAT", "MBL", "COTI", "STPT", "SOL", "CTSI", "HIVE", "CHR", "MDT", "STMX", "IQ", "DGB", "COMP", "SXP", "SNX", "VTHO", "IRIS", "MKR", "DAI", "RUNE", "FIO", "AVA", "BAL", "YFI", "JST", "SRM", "ANT", "CRV", "SAND", "OCEAN", "NMR", "DOT", "LUNA", "RSR", "PAXG", "WNXM", "TRB", "BZRX", "SUSHI", "YFII", "KSM", "EGLD", "DIA", "BEL", "WING", "SWRV", "CREAM", "UNI", "AVAX", "BAKE", "BURGER", "FLM", "CAKE", "SPARTA", "XVS", "ALPHA", "AAVE", "NEAR", "FIL", "INJ", "CTK", "KP3R", "AXS", "HARD", "UNFI", "PROM"]
    },
    "BTC": {
      "value": "BTC",
      "label": "BTC",
      "assets": ["ETH", "LTC", "BNB", "NEO", "BCC", "GAS", "HSR", "MCO", "WTC", "LRC", "QTUM", "YOYO", "OMG", "ZRX", "STRAT", "SNGLS", "BQX", "KNC", "FUN", "SNM", "IOTA", "LINK", "XVG", "SALT", "MDA", "MTL", "SUB", "EOS", "SNT", "ETC", "MTH", "ENG", "DNT", "ZEC", "BNT", "AST", "DASH", "OAX", "ICN", "BTG", "EVX", "REQ", "VIB", "TRX", "POWR", "ARK", "XRP", "MOD", "ENJ", "STORJ", "VEN", "KMD", "RCN", "NULS", "RDN", "XMR", "DLT", "AMB", "BAT", "BCPT", "ARN", "GVT", "CDT", "GXS", "POE", "QSP", "BTS", "XZC", "LSK", "TNT", "FUEL", "MANA", "BCD", "DGD", "ADX", "ADA", "PPT", "CMT", "XLM", "CND", "LEND", "WABI", "TNB", "WAVES", "GTO", "ICX", "OST", "ELF", "AION", "NEBL", "BRD", "EDO", "WINGS", "NAV", "LUN", "TRIG", "APPC", "VIBE", "RLC", "INS", "PIVX", "IOST", "CHAT", "STEEM", "NANO", "VIA", "BLZ", "AE", "RPX", "NCASH", "POA", "ZIL", "ONT", "STORM", "XEM", "WAN", "WPR", "QLC", "SYS", "GRS", "CLOAK", "GNT", "LOOM", "BCN", "REP", "TUSD", "ZEN", "SKY", "CVC", "THETA", "IOTX", "QKC", "AGI", "NXS", "DATA", "SC", "NPXS", "KEY", "NAS", "MFT", "DENT", "ARDR", "HOT", "VET", "DOCK", "POLY", "PHX", "HC", "GO", "PAX", "RVN", "DCR", "MITH", "BCHABC", "BCHSV", "REN", "BTT", "ONG", "FET", "CELR", "MATIC", "ATOM", "PHB", "TFUEL", "ONE", "FTM", "BTCB", "ALGO", "ERD", "DOGE", "DUSK", "ANKR", "WIN", "COS", "COCOS", "TOMO", "PERL", "CHZ", "BAND", "BEAM", "XTZ", "HBAR", "NKN", "STX", "KAVA", "ARPA", "CTXC", "BCH", "TROY", "VITE", "FTT", "OGN", "DREP", "TCT", "WRX", "LTO", "MBL", "COTI", "STPT", "SOL", "CTSI", "HIVE", "CHR", "MDT", "STMX", "PNT", "DGB", "COMP", "SXP", "SNX", "IRIS", "MKR", "DAI", "RUNE", "FIO", "AVA", "BAL", "YFI", "JST", "SRM", "ANT", "CRV", "SAND", "OCEAN", "NMR", "DOT", "LUNA", "IDEX", "RSR", "PAXG", "WNXM", "TRB", "BZRX", "WBTC", "SUSHI", "YFII", "KSM", "EGLD", "DIA", "UMA", "BEL", "WING", "UNI", "NBS", "OXT", "SUN", "AVAX", "HNT", "FLM", "SCRT", "ORN", "UTK", "XVS", "ALPHA", "VIDT", "AAVE", "NEAR", "FIL", "INJ", "AERGO", "AUDIO", "CTK", "BOT", "AKRO", "AXS", "HARD", "RENBTC", "STRAX", "FOR", "UNFI", "ROSE", "SKL", "SUSD", "GLM", "GRT", "JUV", "PSG", "1INCH", "REEF", "OG", "ATM", "ASR", "CELO", "RIF", "BTCST", "TRU", "CKB", "TWT", "FIRO"]
    }
  }
}